import requests

cookies = {
    '_ga': 'GA1.2.1271137375.1742222100',
    '__stripe_mid': '4196de49-8f60-4ec7-a554-45371c77969e057545',
    '_gid': 'GA1.2.422932582.1746976231',
    '_4c_': '%7B%22_4c_s_%22%3A%22HcxJCsMwDAXQu%2Fx1DBKR8i3fRhCHlkAWLXQg%2BO4dVm%2F3Tjwv%2FUBT2hJc3IViE%2Fb%2BvqOduF3XHw80iCul%2B1y41SjmWUt6agmmbcrkzBUTXv8rIqqKfa8xxgc%3D%22%7D',
    'incap_ses_49_2419743': 'eVSGFn7EeQfAMYWLihWuACvjIWgAAAAAuTdXkoGBycB/tZxq93F62g==',
    'SESSION': 'ZTJiYzIyNzQtMzVkYy00ZmRhLTg0MTctZWUwOGEyOTBmYTMw',
    'visid_incap_2419743': '+lIhoEiEQAquvHSbP5SHyKw+F2gAAAAAQ0IPAAAAAAC6XNn82QE0PPdpENEkYdU8',
    '_ga_K3EV0E0N6V': 'GS2.2.s1747051318$o12$g0$t1747051318$j0$l0$h0',
    '__stripe_sid': 'a23f47e3-020d-4d1e-9f3b-7ff297d8b6c8868288',
}

headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
    'content-type': 'application/json',
    'dnt': '1',
    'origin': 'https://prd.realist.com',
    'priority': 'u=1, i',
    'referer': 'https://prd.realist.com/search',
    'sec-ch-ua': '"Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': '"Android"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Mobile Safari/537.36',
    # 'cookie': '_ga=GA1.2.1271137375.1742222100; __stripe_mid=4196de49-8f60-4ec7-a554-45371c77969e057545; _gid=GA1.2.422932582.1746976231; _4c_=%7B%22_4c_s_%22%3A%22HcxJCsMwDAXQu%2Fx1DBKR8i3fRhCHlkAWLXQg%2BO4dVm%2F3Tjwv%2FUBT2hJc3IViE%2Fb%2BvqOduF3XHw80iCul%2B1y41SjmWUt6agmmbcrkzBUTXv8rIqqKfa8xxgc%3D%22%7D; incap_ses_49_2419743=eVSGFn7EeQfAMYWLihWuACvjIWgAAAAAuTdXkoGBycB/tZxq93F62g==; SESSION=ZTJiYzIyNzQtMzVkYy00ZmRhLTg0MTctZWUwOGEyOTBmYTMw; visid_incap_2419743=+lIhoEiEQAquvHSbP5SHyKw+F2gAAAAAQ0IPAAAAAAC6XNn82QE0PPdpENEkYdU8; _ga_K3EV0E0N6V=GS2.2.s1747051318$o12$g0$t1747051318$j0$l0$h0; __stripe_sid=a23f47e3-020d-4d1e-9f3b-7ff297d8b6c8868288',
}

json_data = {
    'searchFields': [
        {
            'fieldCode': 'SITE_ADDRESS',
            'operatorValues': [
                {
                    'operator': 'STARTS_WITH',
                    'values': [
                        '1618 Centennial Dr, Longmont CO 80501',
                    ],
                },
            ],
        },
    ],
    'displayFields': [
        'ABOVE_GRADE_AREA',
        'ACTUAL_SALE_PRICE',
        'ADJUSTED_BLDG_AREA',
        'ALTERNATE_APN',
        'APN',
        'ASSESSED_TOTAL_VAL_AMT',
        'ASSESSED_VALUE_RATIO',
        'BASEMENT_TYPE',
        'BEDROOMS',
        'BUILDING_LIVING_AREA',
        'COUNTY',
        'COUNTY_USE_CODE',
        'CREV_PURCHASE_AGREEMENT_DATE',
        'CREV_SALE_PRICE',
        'DEED_TYPE',
        'DISTRESSED_SALES',
        'EFFECTIVE_YEAR_BUILT',
        'ELEMENTARY_SCHOOL_NAME',
        'FIPS_CODE',
        'FIREPLACE_INDICATOR',
        'FORECLOSURE_STAGE_IND',
        'FOREIGN_COUNTRY',
        'FORE_AUCTION_DT',
        'FORE_RECORDING_DT',
        'FULL_BATHS',
        'HALF_BATHS',
        'HIGH_SCHOOL_NAME',
        'HOUSE_NUMBER_SUFFIX',
        'LAND_TENURE_CODE',
        'LAND_USE_CATEGORY',
        'LEGAL_LOT',
        'LENDER_CODE',
        'LOCAL_TAX_RATE_TOTAL',
        'LOT_ACRES',
        'LOT_SQUARE_FEET',
        'MAIL_OPT_OUT_FLAG',
        'MAP_REFERENCE_1',
        'MAP_REFERENCE_2',
        'MARKET_AREA_WA',
        'MIDDLE_SCHOOL_NAME',
        'MLS_BASEMENT_DESCRIPTION',
        'MLS_BEDROOM',
        'MLS_COMMENTS',
        'MLS_COMMENTS_HIST',
        'MLS_CONTENT',
        'MLS_CURRENT_LIST_PRICE',
        'MLS_FULL_BATH',
        'MLS_HALF_BATH',
        'MLS_LAND_USE',
        'MLS_LISTING_DATE',
        'MLS_LISTING_IND',
        'MLS_LISTING_NBR_HIST',
        'MLS_LISTING_NUMBER',
        'MLS_LIVING_AREA',
        'MLS_ORIGINAL_LIST_PRICE',
        'MLS_PHOTO_ID',
        'MLS_PHOTO_IND',
        'MLS_PHOTO_PATH',
        'MLS_SALE_DATE',
        'MLS_SALE_PRICE',
        'MLS_STATUS',
        'MLS_STD_MLS_STATUS',
        'MLS_STORIES',
        'MLS_TOTAL_AREA',
        'MLS_TOTAL_BATHS',
        'MLS_YEAR_BUILT',
        'MUNICIPALITY_NAME',
        'NEIGHBORHOOD_CODE',
        'NOMINAL_INDICATOR',
        'ONBOARD_NBH_DESC',
        'OWNER_CODE',
        'OWNER_FIRST_NAME',
        'OWNER_LAST_NAME',
        'OWNER_NAME_1',
        'OWNER_NAME_2',
        'OWNER_NAME_MIDDLE',
        'OWNER_OCCUPIED',
        'PARCEL_ID',
        'PARCEL_SEQ_NUMBER',
        'PHONE_NUMBER',
        'POOL',
        'PRICE_PER_SQUARE_FOOT',
        'PRIOR_YEAR_ASSESSED_VALUE',
        'PRIOR_YEAR_PROPERTY_TAX_AMOUNT',
        'PROPERTY_ADDRESS_MODE',
        'PROPERTY_CARRIER_ROUTE',
        'PROPERTY_CITY_NAME',
        'PROPERTY_POST_DIRECTION',
        'PROPERTY_PRE_DIRECTION',
        'PROPERTY_STATE_NAME',
        'PROPERTY_STREET_NAME',
        'PROPERTY_TAX_AMOUNT',
        'PROPERTY_UNIT_NUMBER',
        'PROPERTY_UNIT_NUMBER',
        'PROPERTY_ZIP4',
        'PROPERTY_ZIP_CODE',
        'RANGE_CD',
        'RECORDING_DATE',
        'REO_RECORDING_DATE',
        'ROW_ID',
        'SALE_DATE',
        'SALE_TYPE',
        'SCHOOL_DISTRICT_CODE',
        'SCHOOL_DISTRICT_NAME',
        'SECTION_CD',
        'SEVAX_BUILDING_NAME',
        'SPECIAL_ASSESSMENT_AMOUNT',
        'SPOUSE_LAST_NAME',
        'SPOUSE_NAME_FIRST',
        'SPOUSE_NAME_MIDDLE',
        'STANDARDIZED_HOUSE_NUMBER',
        'STATE_LAND_USE_CODE',
        'STORIES',
        'SUBDIVISION_NAME',
        'SUB_AREA',
        'TAX_AREA_CODE',
        'THREE_QUARTER_BATHS',
        'TITLE_COMPANY',
        'TOTAL_ASSESSED_VALUE',
        'TOTAL_BATHS',
        'TOTAL_BUILDING_AREA',
        'TOTAL_IMPROVEMENT_VALUE',
        'TOTAL_ROOMS',
        'TOWNSHIP',
        'TRACT_NUMBER',
        'TRACT_NUMBER_CA',
        'UNIVERSAL_LAND_USE',
        'YEAR_BUILT',
        'ZONING',
        'ZONING_2_DESC',
        '_id',
        'LAST_VIEWED_PROPERTY_DATE',
    ],
    'totalRecords': 100,
}

response = requests.post('https://prd.realist.com/api/quick-search', cookies=cookies, headers=headers, json=json_data)

# Note: json_data will not be serialized by requests
# exactly as it was in the original request.
#data = '{"searchFields":[{"fieldCode":"SITE_ADDRESS","operatorValues":[{"operator":"STARTS_WITH","values":["1618 Centennial Dr, Longmont CO 80501"]}]}],"displayFields":["ABOVE_GRADE_AREA","ACTUAL_SALE_PRICE","ADJUSTED_BLDG_AREA","ALTERNATE_APN","APN","ASSESSED_TOTAL_VAL_AMT","ASSESSED_VALUE_RATIO","BASEMENT_TYPE","BEDROOMS","BUILDING_LIVING_AREA","COUNTY","COUNTY_USE_CODE","CREV_PURCHASE_AGREEMENT_DATE","CREV_SALE_PRICE","DEED_TYPE","DISTRESSED_SALES","EFFECTIVE_YEAR_BUILT","ELEMENTARY_SCHOOL_NAME","FIPS_CODE","FIREPLACE_INDICATOR","FORECLOSURE_STAGE_IND","FOREIGN_COUNTRY","FORE_AUCTION_DT","FORE_RECORDING_DT","FULL_BATHS","HALF_BATHS","HIGH_SCHOOL_NAME","HOUSE_NUMBER_SUFFIX","LAND_TENURE_CODE","LAND_USE_CATEGORY","LEGAL_LOT","LENDER_CODE","LOCAL_TAX_RATE_TOTAL","LOT_ACRES","LOT_SQUARE_FEET","MAIL_OPT_OUT_FLAG","MAP_REFERENCE_1","MAP_REFERENCE_2","MARKET_AREA_WA","MIDDLE_SCHOOL_NAME","MLS_BASEMENT_DESCRIPTION","MLS_BEDROOM","MLS_COMMENTS","MLS_COMMENTS_HIST","MLS_CONTENT","MLS_CURRENT_LIST_PRICE","MLS_FULL_BATH","MLS_HALF_BATH","MLS_LAND_USE","MLS_LISTING_DATE","MLS_LISTING_IND","MLS_LISTING_NBR_HIST","MLS_LISTING_NUMBER","MLS_LIVING_AREA","MLS_ORIGINAL_LIST_PRICE","MLS_PHOTO_ID","MLS_PHOTO_IND","MLS_PHOTO_PATH","MLS_SALE_DATE","MLS_SALE_PRICE","MLS_STATUS","MLS_STD_MLS_STATUS","MLS_STORIES","MLS_TOTAL_AREA","MLS_TOTAL_BATHS","MLS_YEAR_BUILT","MUNICIPALITY_NAME","NEIGHBORHOOD_CODE","NOMINAL_INDICATOR","ONBOARD_NBH_DESC","OWNER_CODE","OWNER_FIRST_NAME","OWNER_LAST_NAME","OWNER_NAME_1","OWNER_NAME_2","OWNER_NAME_MIDDLE","OWNER_OCCUPIED","PARCEL_ID","PARCEL_SEQ_NUMBER","PHONE_NUMBER","POOL","PRICE_PER_SQUARE_FOOT","PRIOR_YEAR_ASSESSED_VALUE","PRIOR_YEAR_PROPERTY_TAX_AMOUNT","PROPERTY_ADDRESS_MODE","PROPERTY_CARRIER_ROUTE","PROPERTY_CITY_NAME","PROPERTY_POST_DIRECTION","PROPERTY_PRE_DIRECTION","PROPERTY_STATE_NAME","PROPERTY_STREET_NAME","PROPERTY_TAX_AMOUNT","PROPERTY_UNIT_NUMBER","PROPERTY_UNIT_NUMBER","PROPERTY_ZIP4","PROPERTY_ZIP_CODE","RANGE_CD","RECORDING_DATE","REO_RECORDING_DATE","ROW_ID","SALE_DATE","SALE_TYPE","SCHOOL_DISTRICT_CODE","SCHOOL_DISTRICT_NAME","SECTION_CD","SEVAX_BUILDING_NAME","SPECIAL_ASSESSMENT_AMOUNT","SPOUSE_LAST_NAME","SPOUSE_NAME_FIRST","SPOUSE_NAME_MIDDLE","STANDARDIZED_HOUSE_NUMBER","STATE_LAND_USE_CODE","STORIES","SUBDIVISION_NAME","SUB_AREA","TAX_AREA_CODE","THREE_QUARTER_BATHS","TITLE_COMPANY","TOTAL_ASSESSED_VALUE","TOTAL_BATHS","TOTAL_BUILDING_AREA","TOTAL_IMPROVEMENT_VALUE","TOTAL_ROOMS","TOWNSHIP","TRACT_NUMBER","TRACT_NUMBER_CA","UNIVERSAL_LAND_USE","YEAR_BUILT","ZONING","ZONING_2_DESC","_id","LAST_VIEWED_PROPERTY_DATE"],"totalRecords":100}'
#response = requests.post('https://prd.realist.com/api/quick-search', cookies=cookies, headers=headers, data=data)